/**
 * Export Adapters — 真实输出转换器
 *
 * 每个适配器将 narrative store 的数据转换为目标格式的实际文本输出。
 * 支持 WebGAL、JSON、Ink 三种格式的真实转换。
 */

import type { ExportFormatId, ExportResult } from '@/lib/types/export-engine';

// ── Narrative store 状态类型（简化） ──────────────────────────────────────

interface NarrativeStoreState {
  storyNodes: any[];
  nodeEdges: any[];
  variables: any[];
  characters: any[];
  scenes: any[];
  branchPaths: any[];
  qualityChecks: any[];
  narrativeIntents: any[];
  chapterPlans: any[];
  [key: string]: any;
}

// ── 适配器类型 ────────────────────────────────────────────────────────────

export type ExportAdapter = (
  store: NarrativeStoreState,
  options: Record<string, string | boolean | number>
) => ExportResult;

// ── WebGAL 适配器 ─────────────────────────────────────────────────────────

const webgalAdapter: ExportAdapter = (store, options) => {
  const startTime = Date.now();
  const lines: string[] = [];
  const includeBgm = options.includeBgm !== false;
  const includeVoice = options.includeVoice !== false;
  const includeEffect = options.includeEffect !== false;

  lines.push('; WebGAL Script - Generated by ChaseDream Creator Studio');
  lines.push(`; Export Time: ${new Date().toISOString()}`);
  lines.push(`; Nodes: ${store.storyNodes.length}`);
  lines.push('');

  // 按节点生成脚本
  for (const node of store.storyNodes) {
    lines.push(`; === Node: ${node.id} (${node.label || node.type}) ===`);

    // 场景切换
    if (node.sceneId) {
      const scene = store.scenes.find((s: any) => s.id === node.sceneId);
      if (scene) {
        lines.push(`changeBg:${scene.name || scene.id}`);
      }
    }

    // BGM
    if (includeBgm && node.bgm) {
      lines.push(`bgm:${node.bgm}`);
    }

    // 对白
    if (node.dialogue) {
      const character = store.characters.find((c: any) => c.id === node.characterId);
      const charName = character?.name || node.characterId || '旁白';
      if (node.type === 'dialogue') {
        lines.push(`${charName}:${node.dialogue}`);
      } else {
        lines.push(`; ${charName}: ${node.dialogue}`);
      }
    }

    // 语音
    if (includeVoice && node.voiceFile) {
      lines.push(`say:${node.voiceFile}`);
    }

    // 选择节点
    if (node.type === 'choice' && node.choices) {
      lines.push(`; Choice node`);
      for (const choice of node.choices) {
        const targetEdge = store.nodeEdges.find((e: any) => e.from === node.id && e.choiceIndex === choice.index);
        const target = targetEdge?.to || '';
        lines.push(`choose:${choice.text}|${target}`);
      }
    }

    // 条件节点
    if (node.type === 'condition') {
      lines.push(`; Condition: ${node.condition || 'unknown'}`);
      if (includeEffect) {
        lines.push(`; Conditional branch`);
      }
    }

    // 特效
    if (includeEffect && node.transition) {
      lines.push(`setTransition:${node.transition}`);
    }

    lines.push('');
  }

  // 变量声明注释
  if (store.variables.length > 0) {
    lines.push('; === Variables ===');
    for (const v of store.variables) {
      lines.push(`; setVar:${v.id}=${v.defaultValue ?? 0}`);
    }
    lines.push('');
  }

  const content = lines.join('\n');
  const duration = Date.now() - startTime;

  return {
    fileName: `script-${Date.now()}.txt`,
    content,
    fileSize: new Blob([content]).size,
    stats: {
      nodesExported: store.storyNodes.length,
      variablesExported: store.variables.length,
      assetRefsExported: store.storyNodes.filter((n: any) => n.bgm || n.sceneId || n.voiceFile).length,
      skippedItems: [],
      duration,
    },
  };
};

// ── JSON 适配器 ───────────────────────────────────────────────────────────

const jsonAdapter: ExportAdapter = (store, options) => {
  const startTime = Date.now();
  const pretty = options.pretty !== false;
  const includeAssets = options.includeAssets !== false;
  const includeQC = options.includeQC === true;

  const exportData: Record<string, any> = {
    $schema: 'chasedream-creator-studio/v2',
    exportedAt: new Date().toISOString(),
    project: {
      nodeCount: store.storyNodes.length,
      edgeCount: store.nodeEdges.length,
      variableCount: store.variables.length,
      characterCount: store.characters.length,
      sceneCount: store.scenes.length,
    },
    storyNodes: store.storyNodes,
    nodeEdges: store.nodeEdges,
    variables: store.variables,
    characters: store.characters,
    scenes: store.scenes,
  };

  if (includeAssets) {
    exportData.branchPaths = store.branchPaths ?? [];
    exportData.chapterPlans = store.chapterPlans ?? [];
    exportData.narrativeIntents = store.narrativeIntents ?? [];
  }

  if (includeQC) {
    exportData.qualityChecks = store.qualityChecks ?? [];
  }

  const content = pretty ? JSON.stringify(exportData, null, 2) : JSON.stringify(exportData);
  const duration = Date.now() - startTime;

  return {
    fileName: `project-${Date.now()}.json`,
    content,
    fileSize: new Blob([content]).size,
    stats: {
      nodesExported: store.storyNodes.length,
      variablesExported: store.variables.length,
      assetRefsExported: includeAssets ? (store.branchPaths?.length ?? 0) + (store.chapterPlans?.length ?? 0) : 0,
      skippedItems: includeQC ? [] : ['qualityChecks (excluded)'],
      duration,
    },
  };
};

// ── Ink 适配器 ────────────────────────────────────────────────────────────

const inkAdapter: ExportAdapter = (store, options) => {
  const startTime = Date.now();
  const useKnots = options.useKnots !== false;
  const globalVars = options.globalVars !== false;
  const lines: string[] = [];

  lines.push('// Ink Script - Generated by ChaseDream Creator Studio');
  lines.push(`// Export Time: ${new Date().toISOString()}`);
  lines.push('');

  // 全局变量
  if (globalVars && store.variables.length > 0) {
    lines.push('// === Global Variables ===');
    for (const v of store.variables) {
      const val = v.defaultValue ?? 0;
      const type = typeof val === 'number' ? 'INT' : 'STRING';
      if (type === 'INT') {
        lines.push(`VAR ${v.id} = ${val}`);
      } else {
        lines.push(`VAR ${v.id} = "${val}"`);
      }
    }
    lines.push('');
  }

  // 起始 knot
  lines.push('=== start ===');
  lines.push('');

  // 按节点生成 Ink 结构
  for (const node of store.storyNodes) {
    if (useKnots) {
      lines.push(`=== ${node.id} ===`);
    }

    // 对白/叙述文本
    if (node.dialogue) {
      const character = store.characters.find((c: any) => c.id === node.characterId);
      if (character && node.type === 'dialogue') {
        lines.push(`${character.name}: ${node.dialogue}`);
      } else {
        lines.push(node.dialogue);
      }
    }

    // 描述文本
    if (node.description) {
      lines.push(node.description);
    }

    // 选择（使用 Ink 的 choice 语法）
    if (node.type === 'choice' && node.choices) {
      for (const choice of node.choices) {
        const edge = store.nodeEdges.find((e: any) => e.from === node.id && e.choiceIndex === choice.index);
        const target = edge?.to || 'end';
        if (edge?.condition) {
          lines.push(`* {${edge.condition}} ${choice.text} -> ${target}`);
        } else {
          lines.push(`* ${choice.text} -> ${target}`);
        }
      }
    }

    // 条件分支
    if (node.type === 'condition') {
      const outEdges = store.nodeEdges.filter((e: any) => e.from === node.id);
      for (const edge of outEdges) {
        if (edge.condition) {
          lines.push(`{${edge.condition}:`);
          lines.push(`  -> ${edge.to}`);
          lines.push('}');
        } else {
          lines.push(`-> ${edge.to}`);
        }
      }
    }

    // 结局
    if (node.type === 'ending_good' || node.type === 'ending_bad') {
      lines.push(`-> END`);
    } else if (node.type !== 'choice' && node.type !== 'condition') {
      // 默认连接到下一个节点
      const outEdge = store.nodeEdges.find((e: any) => e.from === node.id);
      if (outEdge) {
        lines.push(`-> ${outEdge.to}`);
      }
    }

    lines.push('');
  }

  const content = lines.join('\n');
  const duration = Date.now() - startTime;

  return {
    fileName: `story-${Date.now()}.ink`,
    content,
    fileSize: new Blob([content]).size,
    stats: {
      nodesExported: store.storyNodes.length,
      variablesExported: store.variables.length,
      assetRefsExported: 0,
      skippedItems: [],
      duration,
    },
  };
};

// ── Ren'Py 适配器 ────────────────────────────────────────────────────────

const renpyAdapter: ExportAdapter = (store, _options) => {
  const startTime = Date.now();
  const lines: string[] = [];

  lines.push('# Ren\'Py Script - Generated by ChaseDream Creator Studio');
  lines.push(`# Export Time: ${new Date().toISOString()}`);
  lines.push('');

  // 角色定义
  if (store.characters.length > 0) {
    lines.push('# === Character Definitions ===');
    for (const char of store.characters) {
      const color = char.color || '#ffffff';
      lines.push(`define ${char.id} = Character("${char.name}", color="${color}")`);
    }
    lines.push('');
  }

  // 变量定义
  if (store.variables.length > 0) {
    lines.push('# === Variables ===');
    for (const v of store.variables) {
      lines.push(`default ${v.id} = ${v.defaultValue ?? 0}`);
    }
    lines.push('');
  }

  // 主标签
  lines.push('label start:');

  for (const node of store.storyNodes) {
    lines.push(`    # Node: ${node.id} - ${node.label || node.type}`);

    if (node.dialogue) {
      const character = store.characters.find((c: any) => c.id === node.characterId);
      if (character && node.type === 'dialogue') {
        lines.push(`    ${character.id} "${node.dialogue}"`);
      } else {
        lines.push(`    "${node.dialogue}"`);
      }
    }

    if (node.type === 'choice' && node.choices) {
      lines.push('    menu:');
      for (const choice of node.choices) {
        const edge = store.nodeEdges.find((e: any) => e.from === node.id && e.choiceIndex === choice.index);
        lines.push(`        "${choice.text}":`);
        if (edge) {
          lines.push(`            jump ${edge.to}`);
        }
      }
    }

    if (node.type === 'ending_good' || node.type === 'ending_bad') {
      lines.push('    return');
    }
    lines.push('');
  }

  const content = lines.join('\n');
  const duration = Date.now() - startTime;

  return {
    fileName: `script-${Date.now()}.rpy`,
    content,
    fileSize: new Blob([content]).size,
    stats: {
      nodesExported: store.storyNodes.length,
      variablesExported: store.variables.length,
      assetRefsExported: 0,
      skippedItems: [],
      duration,
    },
  };
};

// ── 适配器注册表 ──────────────────────────────────────────────────────────

const adapterRegistry: Partial<Record<ExportFormatId, ExportAdapter>> = {
  webgal: webgalAdapter,
  json: jsonAdapter,
  ink: inkAdapter,
  renpy: renpyAdapter,
};

/** 获取指定格式的适配器 */
export function getAdapter(formatId: ExportFormatId): ExportAdapter | undefined {
  return adapterRegistry[formatId];
}

/** 检查格式是否有真实适配器 */
export function hasAdapter(formatId: ExportFormatId): boolean {
  return formatId in adapterRegistry;
}

/** 获取所有已实现的格式 ID */
export function getImplementedFormats(): ExportFormatId[] {
  return Object.keys(adapterRegistry) as ExportFormatId[];
}
