// ChaseDream Creator Studio — Detroit 级叙事扩展种子数据
// 基于"幽灵协议"(Ghost Protocol) 叙事宇宙

import type {
  POVConfig, TimedDecisionConfig, SubgraphLock,
  RelationshipMeter, ChapterVariant, DialogueTree,
  Evidence, Clue, Deduction, MoralAxis, PathTimeEstimate,
} from '../studio-data';

// ─── 1. POV 配置（3位主角视角） ─────────────────────────────
export const SEED_POV_CONFIGS: POVConfig[] = [
  {
    id: 'pov-001',
    chapterId: 'ch-01',
    characterId: 'char-agent-ling',
    characterName: '凌',
    switchAfterEvent: 0,
    narrativeStyle: 'first_person',
    narrativeStyleLabel: '第一人称内心独白',
    innerMonologue: '雨水顺着面罩滑落，霓虹的倒影在积水中碎成万片。今夜的任务只有一个——活着把数据带回来。',
  },
  {
    id: 'pov-002',
    chapterId: 'ch-02',
    characterId: 'char-hacker-kai',
    characterName: '凯',
    switchAfterEvent: 2,
    narrativeStyle: 'third_person',
    narrativeStyleLabel: '第三人称观察视角',
    innerMonologue: '凯的指尖在键盘上飞舞，屏幕上瀑布般的数据流映在他瞳孔里。他知道，每一次入侵都是在与死神赛跑。',
  },
  {
    id: 'pov-003',
    chapterId: 'ch-03',
    characterId: 'char-corporate-mei',
    characterName: '梅',
    switchAfterEvent: 1,
    narrativeStyle: 'over_shoulder',
    narrativeStyleLabel: '过肩跟踪视角',
    innerMonologue: '她在摩天大楼的玻璃幕墙前驻足，俯瞰着这座被数据吞噬的城市。双面间谍的日子，比任何人想象的都要孤独。',
  },
  {
    id: 'pov-004',
    chapterId: 'ch-04',
    characterId: 'char-agent-ling',
    characterName: '凌',
    switchAfterEvent: 3,
    narrativeStyle: 'first_person',
    narrativeStyleLabel: '第一人称内心独白',
    innerMonologue: '所有线索都指向同一个方向。真相就在眼前，可代价……也许比任何人都承受不起。',
  },
];

// ─── 2. 限时选择配置 ──────────────────────────────────────
export const SEED_TIMED_DECISIONS: TimedDecisionConfig[] = [
  {
    interactionPointId: 'ip-001',
    timeLimit: 10,
    defaultOptionId: 'opt-silence-001',
    timeoutConsequence: '凌没有开口，线人失去了耐心，转身消失在暗巷中。关键情报就此丢失。',
    timeoutCinematic: 'cinematic_informant_leave.mp4',
    displayStyle: 'bar',
    urgencyAudio: true,
    silenceMeaning: '犹豫不决——线人会将沉默视为不信任',
  },
  {
    interactionPointId: 'ip-002',
    timeLimit: 5,
    defaultOptionId: 'opt-freeze-002',
    timeoutConsequence: '警卫发现了入侵者，警报声撕裂了夜色。潜入路线被迫中止，进入逃亡分支。',
    timeoutCinematic: 'cinematic_alarm_triggered.mp4',
    displayStyle: 'heartbeat',
    urgencyAudio: true,
    silenceMeaning: '惊慌失措——本能反应暴露了位置',
  },
  {
    interactionPointId: 'ip-003',
    timeLimit: 15,
    defaultOptionId: 'opt-refuse-003',
    timeoutConsequence: '梅在等待中没有得到回应，她选择独自行动，按照自己的计划执行渗透。',
    displayStyle: 'circle',
    urgencyAudio: false,
    silenceMeaning: '拒绝回答——梅会按照自己的判断行事',
  },
  {
    interactionPointId: 'ip-004',
    timeLimit: 8,
    timeoutConsequence: 'EMP引爆的最佳窗口期已过，凯只能手动绕过防火墙，难度大幅提升。',
    timeoutCinematic: 'cinematic_emp_window_missed.mp4',
    displayStyle: 'hidden',
    urgencyAudio: true,
    silenceMeaning: '迟疑——在电子战中，一秒的犹豫就是致命的',
  },
];

// ─── 3. 子图锁死配置 ──────────────────────────────────────
export const SEED_SUBGRAPH_LOCKS: SubgraphLock[] = [
  {
    id: 'lock-001',
    triggerType: 'character_death',
    triggerCondition: {
      type: 'atomic',
      targetId: 'var-kai-alive',
      targetType: 'variable',
      operator: 'eq',
      value: 0,
    },
    triggerDescription: '凯在第二章的潜入任务中被企业安保系统捕获并处决',
    lockedNodeIds: ['N20', 'N21', 'N22', 'N23', 'N24'],
    lockedEdges: [
      { from: 'N19', to: 'N20' },
      { from: 'N20', to: 'N25' },
    ],
    replacementNodeId: 'N-replacement-kai-dead',
    reversible: false,
    linkedCharacterId: 'char-hacker-kai',
    lockColor: '#dc2626',
  },
  {
    id: 'lock-002',
    triggerType: 'variable_threshold',
    triggerCondition: {
      type: 'atomic',
      targetId: 'var-trust-ling-kai',
      targetType: 'variable',
      operator: 'lt',
      value: 30,
    },
    triggerDescription: '凌与凯之间的信任值过低，凯拒绝参与最终行动',
    lockedNodeIds: ['N30', 'N31', 'N32'],
    lockedEdges: [
      { from: 'N29', to: 'N30' },
    ],
    replacementNodeId: 'N-replacement-kai-refused',
    reversible: true,
    unlockCondition: {
      type: 'atomic',
      targetId: 'var-trust-ling-kai',
      targetType: 'variable',
      operator: 'gte',
      value: 30,
    },
    linkedCharacterId: 'char-hacker-kai',
    lockColor: '#f59e0b',
  },
  {
    id: 'lock-003',
    triggerType: 'choice_made',
    triggerCondition: {
      type: 'composite',
      operator: 'AND',
      conditions: [
        { type: 'atomic', targetId: 'var-mei-cover-blown', targetType: 'variable', operator: 'eq', value: 1 },
        { type: 'atomic', targetId: 'var-alert-level', targetType: 'variable', operator: 'gte', value: 80 },
      ],
    },
    triggerDescription: '梅的卧底身份暴露且警报等级过高，企业总部进入全面封锁状态',
    lockedNodeIds: ['N35', 'N36', 'N37', 'N38'],
    lockedEdges: [
      { from: 'N34', to: 'N35' },
      { from: 'N35', to: 'N36' },
      { from: 'N36', to: 'N40' },
    ],
    replacementNodeId: 'N-replacement-lockdown',
    reversible: false,
    lockColor: '#7c3aed',
  },
];

// ─── 4. 动态关系计量表 ────────────────────────────────────
export const SEED_RELATIONSHIP_METERS: RelationshipMeter[] = [
  {
    id: 'rel-001',
    characterAId: 'char-agent-ling',
    characterAName: '凌',
    characterBId: 'char-hacker-kai',
    characterBName: '凯',
    relationshipLabel: '信任度',
    currentValue: 45,
    initialValue: 20,
    minValue: -100,
    maxValue: 100,
    thresholds: [
      { value: -80, label: '敌对', narrativeEffect: '凯会拒绝一切合作请求，甚至在关键时刻出卖凌' },
      { value: -30, label: '猜忌', narrativeEffect: '对话中增加讽刺选项，关键情报需要额外说服' },
      { value: 0, label: '陌生', narrativeEffect: '基础合作关系，仅维持任务必需的交流' },
      { value: 40, label: '友好', narrativeEffect: '解锁额外支援选项，凯会主动提供技术援助', unlocksContent: ['dialogue-kai-voluntary-help', 'item-kai-custom-exploit'] },
      { value: 75, label: '至交', narrativeEffect: '凯愿意冒生命危险协助最终任务，解锁隐藏结局「并肩」', unlocksContent: ['dialogue-kai-brotherhood', 'ending-side-by-side', 'scene-kai-sacrifice-option'] },
    ],
    history: [
      { nodeId: 'N02', triggerDescription: '凌在任务简报中对凯的技术能力表示认可', delta: 10, reason: '尊重' },
      { nodeId: 'N06', triggerDescription: '凌在QTE中成功掩护凯撤离', delta: 15, reason: '救命之恩' },
      { nodeId: 'N09', triggerDescription: '凌选择保护数据而非凯的安全', delta: -20, reason: '被抛弃感' },
      { nodeId: 'N14', triggerDescription: '凌冒着暴露风险为凯发送警告信号', delta: 20, reason: '忠诚证明' },
    ],
    linkedVariableId: 'var-trust-ling-kai',
    color: '#3b82f6',
  },
  {
    id: 'rel-002',
    characterAId: 'char-agent-ling',
    characterAName: '凌',
    characterBId: 'char-corporate-mei',
    characterBName: '梅',
    relationshipLabel: '默契度',
    currentValue: 10,
    initialValue: 0,
    minValue: -100,
    maxValue: 100,
    thresholds: [
      { value: -60, label: '互相猜忌', narrativeEffect: '梅可能向企业提供凌的身份信息以自保' },
      { value: -20, label: '貌合神离', narrativeEffect: '合作仅限于信息交换，梅不会承担任何风险' },
      { value: 20, label: '试探合作', narrativeEffect: '梅开始提供内部安保漏洞信息' },
      { value: 50, label: '战略同盟', narrativeEffect: '解锁双人渗透任务线，梅成为可靠内线', unlocksContent: ['mission-duo-infiltration', 'dialogue-mei-secret-channel'] },
      { value: 80, label: '生死之交', narrativeEffect: '梅愿意背叛企业，解锁隐藏结局「新身份」', unlocksContent: ['ending-mei-defection', 'scene-mei-final-stand'] },
    ],
    history: [
      { nodeId: 'N05', triggerDescription: '凌在换装渗透中与梅首次接触', delta: 5, reason: '初次接触' },
      { nodeId: 'N11', triggerDescription: '凌成功完成梅设置的试探任务', delta: 5, reason: '证明实力' },
    ],
    linkedVariableId: 'var-rapport-ling-mei',
    color: '#ec4899',
  },
  {
    id: 'rel-003',
    characterAId: 'char-hacker-kai',
    characterAName: '凯',
    characterBId: 'char-corporate-mei',
    characterBName: '梅',
    relationshipLabel: '好感度',
    currentValue: -15,
    initialValue: -30,
    minValue: -100,
    maxValue: 100,
    thresholds: [
      { value: -70, label: '仇视', narrativeEffect: '凯拒绝任何涉及梅的任务计划' },
      { value: -30, label: '偏见', narrativeEffect: '凯在对话中表现出明显的不信任' },
      { value: 0, label: '中立', narrativeEffect: '凯愿意听取梅的建议但保留意见' },
      { value: 35, label: '好感', narrativeEffect: '凯开始对梅的技术能力产生敬意', unlocksContent: ['dialogue-kai-respects-mei'] },
      { value: 70, label: '信赖', narrativeEffect: '凯与梅建立独立情报通道', unlocksContent: ['intel-channel-kai-mei', 'scene-kai-mei-romance-hint'] },
    ],
    history: [
      { nodeId: 'N08', triggerDescription: '凯得知梅曾是企业安全架构师，对她产生本能抵触', delta: -15, reason: '出身偏见' },
      { nodeId: 'N16', triggerDescription: '梅帮凯修复了一个关键漏洞，凯开始改观', delta: 20, reason: '技术认同' },
      { nodeId: 'N18', triggerDescription: '梅在会议中质疑凯的入侵方案', delta: -10, reason: '理念冲突' },
    ],
    linkedVariableId: 'var-affinity-kai-mei',
    color: '#a855f7',
  },
  {
    id: 'rel-004',
    characterAId: 'char-agent-ling',
    characterAName: '凌',
    characterBId: 'char-director-wu',
    characterBName: '吴主管',
    relationshipLabel: '恐惧值',
    currentValue: 55,
    initialValue: 40,
    minValue: -100,
    maxValue: 100,
    thresholds: [
      { value: -50, label: '蔑视', narrativeEffect: '凌不再将吴视为威胁，对话中增加挑衅选项' },
      { value: -10, label: '冷漠', narrativeEffect: '凌对吴的威胁无动于衷' },
      { value: 30, label: '警惕', narrativeEffect: '凌在吴面前保持距离，对话选项减少' },
      { value: 60, label: '畏惧', narrativeEffect: '凌在吴面前会出现手抖演出，部分果断选项被锁定', unlocksContent: ['dialogue-ling-intimidated'] },
      { value: 90, label: '崩溃', narrativeEffect: '凌可能被迫服从吴的命令，进入屈服结局线', unlocksContent: ['ending-ling-submission'] },
    ],
    history: [
      { nodeId: 'N01', triggerDescription: '序章中吴展示了追踪芯片的全面监控能力', delta: 20, reason: '权力展示' },
      { nodeId: 'N13', triggerDescription: '吴在通讯中威胁凌：如果任务失败，她的家人将承担后果', delta: 15, reason: '家人威胁' },
    ],
    linkedVariableId: 'var-fear-ling-wu',
    color: '#ef4444',
  },
  {
    id: 'rel-005',
    characterAId: 'char-corporate-mei',
    characterAName: '梅',
    characterBId: 'char-director-wu',
    characterBName: '吴主管',
    relationshipLabel: '羁绊',
    currentValue: -40,
    initialValue: 30,
    minValue: -100,
    maxValue: 100,
    thresholds: [
      { value: -70, label: '决裂', narrativeEffect: '梅公开与吴对抗，暴露卧底身份' },
      { value: -30, label: '怨恨', narrativeEffect: '梅开始暗中破坏吴的部署' },
      { value: 0, label: '疏离', narrativeEffect: '梅不再主动与吴沟通' },
      { value: 30, label: '从属', narrativeEffect: '梅维持表面服从，可获得吴的信任情报' },
      { value: 60, label: '忠诚', narrativeEffect: '吴将核心机密对梅开放', unlocksContent: ['intel-wu-masterplan', 'scene-mei-inner-conflict'] },
    ],
    history: [
      { nodeId: 'N01', triggerDescription: '梅曾是吴最信任的下属', delta: 0, reason: '初始状态' },
      { nodeId: 'N10', triggerDescription: '吴在不知情的情况下命令梅执行一项违背她良知的任务', delta: -40, reason: '良知冲突' },
      { nodeId: 'N15', triggerDescription: '梅在表面上完美执行任务，重新赢得吴的部分信任', delta: 10, reason: '伪装服从' },
      { nodeId: 'N22', triggerDescription: '吴发现梅的数据访问记录异常', delta: -20, reason: '怀疑加深' },
    ],
    linkedVariableId: 'var-bond-mei-wu',
    color: '#6366f1',
  },
];

// ─── 5. 章节变体 ──────────────────────────────────────────
export const SEED_CHAPTER_VARIANTS: ChapterVariant[] = [
  {
    id: 'cv-001',
    name: '和平渗透路线',
    activationCondition: {
      type: 'composite',
      operator: 'AND',
      conditions: [
        { type: 'atomic', targetId: 'var-stealth-score', targetType: 'variable', operator: 'gte', value: 60 },
        { type: 'atomic', targetId: 'var-alert-level', targetType: 'variable', operator: 'lt', value: 40 },
      ],
    },
    activationDescription: '凌在前期积累了足够的潜行值，且警报等级较低，可以选择无声渗透方案',
    events: [
      { id: 'evt-cv001-1', title: '暗道潜入', description: '通过建筑维护通道无声进入企业数据中心，避开所有安保巡逻路线。' },
      { id: 'evt-cv001-2', title: '数据窃取', description: '凯远程协助破解加密层，凌在服务器机房中安静地复制核心数据。' },
      { id: 'evt-cv001-3', title: '幽灵撤离', description: '从通风管道原路返回，全程未被发现。监控录像中只留下一道模糊的残影。' },
    ],
    emotionArc: '压抑→紧张→释然→成就感',
    themeQuestion: '在不被任何人察觉的情况下完成使命，这是否就是间谍的终极形态？',
    visualTone: '冷蓝色调，低饱和度，光影对比强烈',
    linkedConsequenceIds: ['csq-stealth-success', 'csq-data-obtained'],
  },
  {
    id: 'cv-002',
    name: '强攻突破路线',
    activationCondition: {
      type: 'composite',
      operator: 'AND',
      conditions: [
        { type: 'atomic', targetId: 'var-stealth-score', targetType: 'variable', operator: 'lt', value: 40 },
        { type: 'atomic', targetId: 'var-alert-level', targetType: 'variable', operator: 'gte', value: 60 },
      ],
    },
    activationDescription: '潜行值不足或警报等级过高，凌被迫采取强攻方案正面突入',
    events: [
      { id: 'evt-cv002-1', title: 'EMP轰炸', description: '凯远程引爆预置的EMP装置，大楼安保系统瞬间瘫痪。凌趁混乱冲入正门。' },
      { id: 'evt-cv002-2', title: '枪战突围', description: '与武装警卫在大楼走廊中展开激烈交火，多个QTE序列决定生死。' },
      { id: 'evt-cv002-3', title: '代价撤离', description: '虽然拿到了数据，但凌身受重伤，撤离途中需要凯亲自接应。' },
    ],
    emotionArc: '紧张→激烈→绝望→惨胜',
    themeQuestion: '为了真相付出血的代价值得吗？',
    visualTone: '暖红色调，高饱和度，画面抖动，爆炸光效',
    linkedConsequenceIds: ['csq-combat-damage', 'csq-injury-penalty'],
  },
  {
    id: 'cv-003',
    name: '梅的内线路线',
    activationCondition: {
      type: 'composite',
      operator: 'AND',
      conditions: [
        { type: 'atomic', targetId: 'var-rapport-ling-mei', targetType: 'variable', operator: 'gte', value: 50 },
        { type: 'atomic', targetId: 'var-mei-cover-blown', targetType: 'variable', operator: 'eq', value: 0 },
      ],
    },
    activationDescription: '凌与梅建立了足够的默契，且梅的卧底身份尚未暴露，可通过内线通道完成任务',
    events: [
      { id: 'evt-cv003-1', title: '内部接应', description: '梅以安全审查为名开放了数据中心的临时访问权限，凌以维护工程师身份进入。' },
      { id: 'evt-cv003-2', title: '双线操作', description: '梅在控制室掩护凌的行动，同时应对吴主管的突击检查——一段惊险的双视角交替叙事。' },
      { id: 'evt-cv003-3', title: '完美脱身', description: '梅利用权限清除了凌的入侵记录，两人分别从不同出口离开，不留任何痕迹。' },
    ],
    emotionArc: '期待→惊险→默契→信任升华',
    themeQuestion: '当你开始信任一个来自敌方阵营的人，你自己是否也在变成叛徒？',
    visualTone: '青绿色调，科技感强烈，分屏叙事',
    linkedConsequenceIds: ['csq-mei-trust-boost', 'csq-clean-operation'],
  },
];

// ─── 6. 对话树 ────────────────────────────────────────────
export const SEED_DIALOGUE_TREES: DialogueTree[] = [
  {
    id: 'dlg-001',
    parentNodeId: 'N03',
    name: '暗巷遭遇线人',
    npcId: 'char-informant-ghost',
    npcName: '幽灵',
    startNodeId: 'dlg001-n1',
    trackChoices: true,
    repeatable: false,
    triggerCondition: {
      type: 'atomic',
      targetId: 'var-ghost-met',
      targetType: 'variable',
      operator: 'eq',
      value: 0,
    },
    outcomeSummary: '根据凌的态度和选择，线人可能提供完整情报（高价值）、部分情报（中等）或直接离开（零价值）。此次对话奠定凌在地下世界中的信誉基调。',
    nodes: [
      {
        id: 'dlg001-n1',
        speakerId: 'char-informant-ghost',
        speakerName: '幽灵',
        text: '你就是"凌"？听说你最近在找芯片的事。我手里有些东西，但你得让我知道……你值不值得我冒这个险。',
        performance: '幽灵从暗处走出，面容被全息面具遮掩，声音经过变声处理',
        choices: [
          {
            id: 'dlg001-c1',
            text: '值不值得不是你说了算的。把情报给我，我保你安全。',
            tone: 'intimidating',
            nextNodeId: 'dlg001-n2',
            variableEffects: [{ variableId: 'var-intimidation', delta: 10 }],
            relationshipEffects: [{ meterId: 'rel-ghost', delta: -10 }],
            oneTime: false,
            narrativeSignificance: '展示强硬姿态，可能震慑线人但也可能引起反感',
          },
          {
            id: 'dlg001-c2',
            text: '我们都在冒险。告诉我你知道的，我会在事成之后确保你拿到应有的报酬。',
            tone: 'neutral',
            nextNodeId: 'dlg001-n3',
            relationshipEffects: [{ meterId: 'rel-ghost', delta: 5 }],
            oneTime: false,
          },
          {
            id: 'dlg001-c3',
            text: '我理解你的处境。如果你不信任我，我们可以先交换一些对彼此都有用的信息。',
            tone: 'empathetic',
            nextNodeId: 'dlg001-n4',
            relationshipEffects: [{ meterId: 'rel-ghost', delta: 15 }],
            oneTime: false,
            narrativeSignificance: '展现同理心，建立信任基础',
          },
        ],
        isTerminal: false,
        interruptResponse: '幽灵冷冷地扫了你一眼："别打断我说话。"',
      },
      {
        id: 'dlg001-n2',
        speakerId: 'char-informant-ghost',
        speakerName: '幽灵',
        text: '哈，就这？你以为威胁我就能得到想要的？我在这行混了十年，见过比你狠十倍的人。',
        performance: '幽灵后退一步，手摸向腰间的信号干扰器',
        choices: [
          {
            id: 'dlg001-c4',
            text: '……抱歉，我话说重了。重新来。',
            tone: 'empathetic',
            nextNodeId: 'dlg001-n4',
            relationshipEffects: [{ meterId: 'rel-ghost', delta: 5 }],
            oneTime: true,
            narrativeSignificance: '罕见的示弱，可能赢得线人的尊重',
          },
          {
            id: 'dlg001-c5',
            text: '十年？那你应该很清楚，不跟我合作对你没有任何好处。',
            tone: 'hostile',
            nextNodeId: 'dlg001-n5',
            variableEffects: [{ variableId: 'var-intimidation', delta: 15 }],
            relationshipEffects: [{ meterId: 'rel-ghost', delta: -20 }],
            oneTime: false,
          },
        ],
        isTerminal: false,
      },
      {
        id: 'dlg001-n3',
        speakerId: 'char-informant-ghost',
        speakerName: '幽灵',
        text: '报酬？行吧，算你务实。芯片项目的核心架构师叫"回声"，他在企业的第七区实验室工作。不过……他最近好像想叛逃。',
        performance: '幽灵从口袋中掏出一个加密U盘，但没有递过来',
        choices: [
          {
            id: 'dlg001-c6',
            text: '"回声"是谁？我需要更多细节。',
            tone: 'neutral',
            nextNodeId: 'dlg001-n6',
            oneTime: false,
          },
          {
            id: 'dlg001-c7',
            text: 'U盘里有他的位置和联络方式吗？',
            tone: 'neutral',
            nextNodeId: 'dlg001-n6',
            variableEffects: [{ variableId: 'var-intel-progress', delta: 10 }],
            oneTime: false,
          },
        ],
        isTerminal: false,
      },
      {
        id: 'dlg001-n4',
        speakerId: 'char-informant-ghost',
        speakerName: '幽灵',
        text: '……你这人倒是挺有意思。好吧，我信你一次。芯片项目的核心架构师代号"回声"，他掌握着所有关键数据。而且——他正在考虑叛逃。',
        performance: '幽灵放松了戒备，将加密U盘递到凌面前',
        choices: [
          {
            id: 'dlg001-c8',
            text: '谢谢你。这份情报对我很重要。你的安全我也会负责的。',
            tone: 'friendly',
            nextNodeId: 'dlg001-n6',
            variableEffects: [{ variableId: 'var-intel-progress', delta: 20 }],
            relationshipEffects: [{ meterId: 'rel-ghost', delta: 10 }],
            oneTime: false,
            narrativeSignificance: '建立长期情报关系',
          },
          {
            id: 'dlg001-c9',
            text: '"回声"要叛逃？他手里有什么筹码？',
            tone: 'neutral',
            nextNodeId: 'dlg001-n6',
            variableEffects: [{ variableId: 'var-intel-progress', delta: 15 }],
            oneTime: false,
          },
        ],
        isTerminal: false,
      },
      {
        id: 'dlg001-n5',
        speakerId: 'char-informant-ghost',
        speakerName: '幽灵',
        text: '你走吧。我没什么好跟你说的了。下次见面……希望你不是以敌人的身份出现。',
        performance: '幽灵启动了信号干扰器，身形在全息伪装中消失',
        choices: [],
        isTerminal: true,
        exitNodeId: 'N03-after-fail',
      },
      {
        id: 'dlg001-n6',
        speakerId: 'char-informant-ghost',
        speakerName: '幽灵',
        text: '记住，"回声"只信任能证明实力的人。如果你想去见他，先搞定第七区的外围防御。祝你好运……凌。',
        performance: '幽灵将U盘交给凌后，迅速消失在暗巷深处',
        choices: [],
        isTerminal: true,
        exitNodeId: 'N04',
      },
    ],
  },
  {
    id: 'dlg-002',
    parentNodeId: 'N08',
    name: '凯的技术争论',
    npcId: 'char-hacker-kai',
    npcName: '凯',
    startNodeId: 'dlg002-n1',
    trackChoices: true,
    repeatable: false,
    triggerCondition: {
      type: 'composite',
      operator: 'AND',
      conditions: [
        { type: 'atomic', targetId: 'var-trust-ling-kai', targetType: 'variable', operator: 'gte', value: 20 },
        { type: 'atomic', targetId: 'var-data-obtained', targetType: 'variable', operator: 'eq', value: 1 },
      ],
    },
    outcomeSummary: '凌与凯就如何处理获取到的数据产生分歧。选择结果将影响两人关系走向以及后续任务的技术路线。',
    nodes: [
      {
        id: 'dlg002-n1',
        speakerId: 'char-hacker-kai',
        speakerName: '凯',
        text: '数据拿到了，但我看了一下……这里面不只有芯片架构，还有一份平民监控名单。如果我们把整份数据公开，那些被监控的人也能得到解脱。',
        performance: '凯靠在椅背上，手指敲着桌面，表情复杂',
        choices: [
          {
            id: 'dlg002-c1',
            text: '不行。我们的任务是芯片架构，不是当英雄。公开全部数据会暴露我们。',
            tone: 'cold',
            nextNodeId: 'dlg002-n2',
            variableEffects: [{ variableId: 'var-moral-pragmatic', delta: 15 }],
            relationshipEffects: [{ meterId: 'rel-001', delta: -10 }],
            oneTime: false,
            narrativeSignificance: '任务优先的冷酷决策，损害凯对凌的信任',
          },
          {
            id: 'dlg002-c2',
            text: '你说得对。那些被监控的人也是受害者。我们想办法安全地公开监控名单部分。',
            tone: 'empathetic',
            nextNodeId: 'dlg002-n3',
            variableEffects: [{ variableId: 'var-moral-idealistic', delta: 15 }],
            relationshipEffects: [{ meterId: 'rel-001', delta: 15 }],
            oneTime: false,
            narrativeSignificance: '理想主义选择，加深与凯的信任但增加风险',
          },
          {
            id: 'dlg002-c3',
            text: '先别急。让我看看这份名单的规模，我们再决定怎么处理。',
            tone: 'neutral',
            nextNodeId: 'dlg002-n4',
            oneTime: false,
          },
        ],
        isTerminal: false,
        interruptResponse: '凯抬起头看着你："这事不能拖。"',
      },
      {
        id: 'dlg002-n2',
        speakerId: 'char-hacker-kai',
        speakerName: '凯',
        text: '……我就知道。你们这些"特工"永远只会考虑任务。那些名单上的人呢？他们就是数字？',
        performance: '凯站了起来，语气中带着压抑的愤怒',
        choices: [
          {
            id: 'dlg002-c4',
            text: '我不是不在乎他们。但现在暴露意味着所有人的努力都白费了。',
            tone: 'empathetic',
            nextNodeId: 'dlg002-n5',
            relationshipEffects: [{ meterId: 'rel-001', delta: 5 }],
            oneTime: true,
          },
          {
            id: 'dlg002-c5',
            text: '别感情用事。如果你不能服从计划，我找别人。',
            tone: 'hostile',
            nextNodeId: 'dlg002-n5',
            variableEffects: [{ variableId: 'var-moral-pragmatic', delta: 10 }],
            relationshipEffects: [{ meterId: 'rel-001', delta: -25 }],
            oneTime: true,
            narrativeSignificance: '可能导致凯在后续任务中消极合作',
          },
        ],
        isTerminal: false,
      },
      {
        id: 'dlg002-n3',
        speakerId: 'char-hacker-kai',
        speakerName: '凯',
        text: '好！我就知道你不是那种冷血特工。给我一点时间，我可以把监控名单通过匿名渠道泄露给地下媒体。芯片数据我们自己留着。',
        performance: '凯露出了难得的笑容，迅速转向键盘开始操作',
        choices: [
          {
            id: 'dlg002-c6',
            text: '注意匿名性。如果被追溯到我们，一切都完了。',
            tone: 'neutral',
            nextNodeId: 'dlg002-n5',
            variableEffects: [{ variableId: 'var-alert-level', delta: 5 }],
            oneTime: false,
          },
          {
            id: 'dlg002-c7',
            text: '凯……谢谢你。有你在真好。',
            tone: 'friendly',
            nextNodeId: 'dlg002-n5',
            relationshipEffects: [{ meterId: 'rel-001', delta: 10 }],
            oneTime: true,
            narrativeSignificance: '情感连接加深，凯将记住这句话',
          },
        ],
        isTerminal: false,
      },
      {
        id: 'dlg002-n4',
        speakerId: 'char-hacker-kai',
        speakerName: '凯',
        text: '规模？……让我算算。大概有两万三千名平民的完整行为数据。包括位置、通讯记录、甚至生物特征。这些人完全不知道自己在被监控。',
        performance: '凯把屏幕转向凌，密密麻麻的条目滚过屏幕',
        choices: [
          {
            id: 'dlg002-c8',
            text: '两万多人……这比我想象的严重得多。我们必须做点什么。',
            tone: 'empathetic',
            nextNodeId: 'dlg002-n3',
            variableEffects: [{ variableId: 'var-moral-idealistic', delta: 10 }],
            relationshipEffects: [{ meterId: 'rel-001', delta: 10 }],
            oneTime: false,
          },
          {
            id: 'dlg002-c9',
            text: '数据量太大，处理起来风险太高。先完成任务再说。',
            tone: 'cold',
            nextNodeId: 'dlg002-n2',
            variableEffects: [{ variableId: 'var-moral-pragmatic', delta: 10 }],
            relationshipEffects: [{ meterId: 'rel-001', delta: -5 }],
            oneTime: false,
          },
        ],
        isTerminal: false,
      },
      {
        id: 'dlg002-n5',
        speakerId: 'char-hacker-kai',
        speakerName: '凯',
        text: '行，那就这样。不管你怎么选，我都跟你走到底……至少现在还是。下一步怎么办？',
        performance: '凯关掉了多余屏幕，把注意力转回凌',
        choices: [],
        isTerminal: true,
        exitNodeId: 'N09',
      },
    ],
  },
];

// ─── 7. 调查证据 ──────────────────────────────────────────
export const SEED_EVIDENCE: Evidence[] = [
  {
    id: 'ev-001',
    name: '加密芯片碎片',
    type: 'physical',
    typeLabel: '物证',
    description: '在企业大厦垃圾通道中发现的芯片碎片，表面刻有"Project Chimera"字样。虽然数据层已损坏，但物理结构暗示这是一种军用级加密方案。',
    discoveredAtNodeId: 'N04',
    discoveryCondition: {
      type: 'atomic',
      targetId: 'var-search-chute',
      targetType: 'variable',
      operator: 'eq',
      value: 1,
    },
    relatedCharacterIds: ['char-agent-ling'],
    relatedSceneIds: ['scene-corp-tower'],
    importance: 4,
    discovered: true,
    discoveryNarrative: '凌在垃圾通道的深处摸到了一块不寻常的碎片。当她用手电照亮时，金属表面反射出微弱的光芒——上面蚀刻着三个字："Project Chimera"。',
  },
  {
    id: 'ev-002',
    name: '线人录音',
    type: 'testimonial',
    typeLabel: '证言',
    description: '线人"幽灵"提供的加密录音，内容涉及企业高层秘密会议讨论"奇美拉计划"的片段。录音中提到一个代号"回声"的架构师。',
    discoveredAtNodeId: 'N03',
    relatedCharacterIds: ['char-informant-ghost', 'char-agent-ling'],
    importance: 3,
    discovered: true,
    discoveryNarrative: '幽灵将录音笔扔过来的时候，手都在微微颤抖。"这是我从一个醉酒的秘书那里搞到的。听的时候把声音调小……他们无处不在。"',
  },
  {
    id: 'ev-003',
    name: '安保日志副本',
    type: 'documentary',
    typeLabel: '文档',
    description: '梅从企业内部系统复制的安保值班日志，记录了第七区实验室在深夜时段的异常访问记录。多名未登记人员使用了最高权限进入。',
    discoveredAtNodeId: 'N12',
    discoveryCondition: {
      type: 'composite',
      operator: 'AND',
      conditions: [
        { type: 'atomic', targetId: 'var-rapport-ling-mei', targetType: 'variable', operator: 'gte', value: 30 },
        { type: 'atomic', targetId: 'var-mei-cover-blown', targetType: 'variable', operator: 'eq', value: 0 },
      ],
    },
    relatedCharacterIds: ['char-corporate-mei'],
    relatedSceneIds: ['scene-lab-floor-7'],
    importance: 5,
    discovered: false,
    discoveryNarrative: '梅在深夜发来了一条加密信息。附件是一份看似普通的排班表，但凌很快注意到——第七区在凌晨三点到五点之间，出现了三个没有对应员工编号的访问记录。',
  },
  {
    id: 'ev-004',
    name: '网络入侵痕迹',
    type: 'digital',
    typeLabel: '电子证据',
    description: '凯在企业防火墙日志中发现的外部入侵痕迹。攻击者使用了一种罕见的AI辅助渗透技术，手法与已知的"暗网联盟"组织高度吻合。',
    discoveredAtNodeId: 'N07',
    relatedCharacterIds: ['char-hacker-kai'],
    relatedSceneIds: ['scene-cyber-space'],
    importance: 4,
    discovered: true,
    discoveryNarrative: '凯的手指突然停在了键盘上。"等等……这不是普通的入侵。看这个数据包结构——有人在用AI自动生成攻击向量。我只在一个地方见过这种手法。"他的脸色变了。',
  },
  {
    id: 'ev-005',
    name: '目击者描述',
    type: 'testimonial',
    typeLabel: '证言',
    description: '一名已离职的前保安声称，他在值班期间多次看到穿白色实验服的人员携带大型设备进出第七区，且所有运输都发生在深夜。',
    discoveredAtNodeId: 'N15',
    relatedCharacterIds: ['char-agent-ling'],
    relatedSceneIds: ['scene-underground-bar'],
    importance: 2,
    discovered: false,
    discoveryNarrative: '在地下酒吧最昏暗的角落，一个中年男人紧张地四处张望。"我只说一次。那些白大褂……他们搬的东西，像是服务器，但又不完全是。而且每次搬完，那层楼都会多一股……臭氧的味道。"',
  },
  {
    id: 'ev-006',
    name: '电力消耗异常报告',
    type: 'circumstantial',
    typeLabel: '间接证据',
    description: '从城市公共事业数据库中调取的企业大厦用电记录显示，第七区的电力消耗是其他楼层的17倍，且主要集中在凌晨时段。这种量级暗示着大规模计算设备的运行。',
    discoveredAtNodeId: 'N18',
    discoveryCondition: {
      type: 'atomic',
      targetId: 'var-intel-progress',
      targetType: 'variable',
      operator: 'gte',
      value: 40,
    },
    relatedCharacterIds: ['char-hacker-kai'],
    importance: 3,
    discovered: false,
    discoveryNarrative: '凯调出了大厦的电力消耗曲线图，指着凌晨三点那条飙升的红色曲线说："看到了吗？每天凌晨三点到五点，这栋楼的用电量暴增十七倍。这可不是在加班那么简单。"',
  },
];

// ─── 8. 线索 ─────────────────────────────────────────────
export const SEED_CLUES: Clue[] = [
  {
    id: 'clue-001',
    name: '第七区的秘密实验室',
    description: '多条证据指向企业大厦第七区存在一个未经公开的秘密实验室。深夜时段的异常访问、超额电力消耗以及物理证据共同描绘出一个隐藏的真相——那里正在进行某种大规模计算项目。',
    requiredEvidenceIds: ['ev-001', 'ev-003', 'ev-006'],
    pointsTo: 'ded-001',
    revelationText: '所有线索汇聚成了一个令人不安的画面：企业大厦第七区并非普通的办公楼层，而是一个秘密运作的实验室。加密芯片碎片、深夜的未登记访问者，以及异常到离谱的电力消耗——一切都在指向一个结论：那里隐藏着"奇美拉计划"的核心。',
    activated: true,
  },
  {
    id: 'clue-002',
    name: '暗网联盟的介入',
    description: '网络入侵痕迹与线人情报交叉比对后发现，一个名为"暗网联盟"的外部组织也在关注奇美拉计划，且他们的渗透技术远超一般黑客组织。这暗示着项目背后可能有更大的利益方。',
    requiredEvidenceIds: ['ev-002', 'ev-004'],
    pointsTo: 'ded-001',
    revelationText: '当凯将入侵日志与幽灵的录音并排比对时，两人的脸色同时沉了下来。暗网联盟——那个传说中由前军方黑客组成的地下组织——居然也在追踪奇美拉计划。而他们的渗透手法……像是有人从内部泄露了防火墙架构。',
    activated: false,
  },
  {
    id: 'clue-003',
    name: '回声的真实身份',
    description: '结合前保安的目击描述和网络入侵的技术特征，"回声"可能不仅仅是一个普通的架构师。他所掌握的技术与暗网联盟使用的AI辅助渗透如出一辙，暗示他可能是联盟安插在企业内部的卧底。',
    requiredEvidenceIds: ['ev-004', 'ev-005', 'ev-002'],
    pointsTo: 'ded-002',
    revelationText: '碎片拼合在一起。"回声"——那个传说中想要叛逃的架构师——他手上的技术和暗网联盟使用的AI渗透工具惊人地相似。这意味着他从来就不是一个单纯的企业员工。他是在等待时机……等待一个把所有秘密都带走的时机。',
    activated: false,
  },
];

// ─── 9. 推理 ─────────────────────────────────────────────
export const SEED_DEDUCTIONS: Deduction[] = [
  {
    id: 'ded-001',
    question: '奇美拉计划的真正目的是什么？',
    description: '基于收集到的证据和线索，推断企业秘密项目"奇美拉"的核心目标。这一推理将决定凌后续的调查方向和最终行动方案。',
    locationNodeId: 'N20',
    timeLimit: 0,
    failureConsequence: '凌无法形成有效推断，后续行动将陷入盲目摸索。任务时间线被迫延长，增加暴露风险。',
    conclusions: [
      {
        id: 'conc-001-a',
        text: '奇美拉是一个大规模AI监控系统，旨在利用城市基础设施对全体市民进行实时行为预测和控制。',
        isCorrect: true,
        requiredClueIds: ['clue-001', 'clue-002'],
        narrativeConsequence: '凌意识到了项目的真正恐怖之处——这不仅仅是商业间谍活动，而是关乎数百万人的自由。她决定将调查升级为全面揭露行动。',
        variableEffects: [
          { variableId: 'var-truth', delta: 30 },
          { variableId: 'var-mission-scope', delta: 50 },
        ],
      },
      {
        id: 'conc-001-b',
        text: '奇美拉是一个军用级加密通讯项目，企业正在为军方开发下一代安全通讯协议。',
        isCorrect: false,
        requiredClueIds: ['clue-001'],
        narrativeConsequence: '凌将调查方向转向军方关联企业，浪费了大量时间和资源。当她发现方向错误时，企业的防御已经升级，后续渗透难度大幅提升。',
        variableEffects: [
          { variableId: 'var-alert-level', delta: 20 },
          { variableId: 'var-time-wasted', delta: 1 },
        ],
      },
      {
        id: 'conc-001-c',
        text: '奇美拉只是一个普通的芯片研发项目，异常数据可能只是内部测试的副作用。',
        isCorrect: false,
        requiredClueIds: [],
        narrativeConsequence: '凌低估了项目的威胁等级，向组织汇报了"低优先级"的结论。这个错误判断让她在后续完全没有准备的情况下遭遇了真正的危机。',
        variableEffects: [
          { variableId: 'var-truth', delta: -10 },
          { variableId: 'var-preparedness', delta: -20 },
        ],
      },
    ],
  },
  {
    id: 'ded-002',
    question: '"回声"是可以信任的盟友，还是另一个陷阱？',
    description: '凌必须判断架构师"回声"的叛逃意图是真是假。如果他是真诚的，那将是获取核心数据的最佳途径；但如果这是企业设下的圈套，凌将面临灭顶之灾。',
    locationNodeId: 'N25',
    timeLimit: 30,
    failureConsequence: '凌在犹豫中错过了接触"回声"的最佳窗口期。他独自完成了数据转移并消失，凌失去了获取核心数据的最后机会。',
    conclusions: [
      {
        id: 'conc-002-a',
        text: '"回声"是暗网联盟安插的卧底，他的叛逃是为了将数据转移给联盟而非真心想要推翻企业。应该阻止他。',
        isCorrect: true,
        requiredClueIds: ['clue-003', 'clue-002'],
        narrativeConsequence: '凌决定在"回声"完成数据转移之前拦截他。一场三方博弈就此展开——凌代表组织，"回声"代表暗网联盟，而企业安保则是第三方力量。',
        variableEffects: [
          { variableId: 'var-truth', delta: 20 },
          { variableId: 'var-enemy-awareness', delta: 15 },
        ],
      },
      {
        id: 'conc-002-b',
        text: '"回声"是真心想叛逃的良心发现者，应该全力支持他的行动并建立合作关系。',
        isCorrect: false,
        requiredClueIds: ['clue-001'],
        narrativeConsequence: '凌选择信任"回声"并提供了撤离支援。然而在关键时刻，"回声"将凌的位置信息出卖给了暗网联盟作为投名状。凌陷入了两面受敌的绝境。',
        variableEffects: [
          { variableId: 'var-trust-betrayed', delta: 1 },
          { variableId: 'var-danger-level', delta: 30 },
        ],
      },
      {
        id: 'conc-002-c',
        text: '"回声"是吴主管故意放出的诱饵，目的是引凌现身并一网打尽。应该彻底回避接触。',
        isCorrect: false,
        requiredClueIds: [],
        narrativeConsequence: '凌选择了最保守的策略，完全避开了"回声"。虽然保全了自身安全，但奇美拉计划的核心数据也随"回声"的消失而永远沉入了数据的深渊。任务以不完整的情报收场。',
        variableEffects: [
          { variableId: 'var-truth', delta: 5 },
          { variableId: 'var-mission-completion', delta: -30 },
        ],
      },
    ],
  },
];

// ─── 10. 道德轴 ───────────────────────────────────────────
export const SEED_MORAL_AXES: MoralAxis[] = [
  {
    id: 'moral-001',
    name: '忠诚度',
    negativeLabel: '绝对服从',
    positiveLabel: '个人良知',
    currentValue: -10,
    initialValue: -30,
    zones: [
      {
        min: -100,
        max: -60,
        label: '完美棋子',
        narrativeTone: '冰冷、高效、不带任何犹豫的执行者。内心独白极简，只有任务参数。',
        unlockedContent: ['dialogue-ling-obedient', 'skill-blind-execution'],
      },
      {
        min: -59,
        max: -20,
        label: '忠诚执行者',
        narrativeTone: '偶尔产生疑问但会迅速压制。仍然以任务为最高优先级。',
      },
      {
        min: -19,
        max: 19,
        label: '摇摆不定',
        narrativeTone: '任务与良知之间的拉锯越来越明显。内心独白开始出现自我质疑。',
        unlockedContent: ['inner-monologue-doubt', 'dialogue-ling-questioning'],
      },
      {
        min: 20,
        max: 59,
        label: '良知觉醒',
        narrativeTone: '开始质疑组织的真正目的。会为了保护无辜者而违抗部分命令。',
        unlockedContent: ['dialogue-ling-defiant', 'mission-side-objective-protect'],
      },
      {
        min: 60,
        max: 100,
        label: '反叛者',
        narrativeTone: '彻底站在了组织的对立面。内心独白充满愤怒与决心，准备揭露一切真相。',
        unlockedContent: ['ending-whistleblower', 'dialogue-ling-revolution', 'scene-ling-burn-badge'],
      },
    ],
    affectsEndings: ['ending-loyal-soldier', 'ending-conflicted-agent', 'ending-whistleblower', 'ending-revolution'],
    affectsNPCAttitudes: [
      { characterId: 'char-director-wu', threshold: -40, attitudeChange: '吴主管对凌更加信任，分配核心任务' },
      { characterId: 'char-director-wu', threshold: 40, attitudeChange: '吴主管开始怀疑凌的忠诚度，加强监控' },
      { characterId: 'char-hacker-kai', threshold: 30, attitudeChange: '凯对凌产生敬意，认为她不是普通的走狗' },
      { characterId: 'char-corporate-mei', threshold: 50, attitudeChange: '梅视凌为潜在盟友，愿意分享更多内部情报' },
    ],
    gatesChoices: [
      { choiceOptionId: 'opt-obey-order', requiredRange: { min: -100, max: 0 } },
      { choiceOptionId: 'opt-defy-order', requiredRange: { min: 20, max: 100 } },
      { choiceOptionId: 'opt-sabotage-mission', requiredRange: { min: 60, max: 100 } },
      { choiceOptionId: 'opt-report-to-director', requiredRange: { min: -100, max: -20 } },
    ],
    gradientColors: ['#1e3a5f', '#f59e0b'],
    description: '衡量凌在组织命令与个人道德之间的立场。偏向负极时，凌是一个完美的情报机器；偏向正极时，她逐渐变成一个有良知的反叛者。',
  },
  {
    id: 'moral-002',
    name: '人性指数',
    negativeLabel: '机械效率',
    positiveLabel: '人性共情',
    currentValue: 15,
    initialValue: 0,
    zones: [
      {
        min: -100,
        max: -60,
        label: '冷酷机器',
        narrativeTone: '凌的决策完全基于数据和概率，不带任何情感色彩。NPC会形容她"不像个活人"。',
        unlockedContent: ['skill-tactical-optimization', 'dialogue-others-fear-ling'],
      },
      {
        min: -59,
        max: -20,
        label: '理性至上',
        narrativeTone: '偶尔展露人性，但在关键时刻总是选择最优解而非最人性的选择。',
      },
      {
        min: -19,
        max: 19,
        label: '灰色地带',
        narrativeTone: '效率与同情心之间的平衡点。凌会在不影响任务的前提下尽量保护他人。',
        unlockedContent: ['dialogue-ling-balanced', 'scene-ling-hesitation'],
      },
      {
        min: 20,
        max: 59,
        label: '共情觉醒',
        narrativeTone: '凌开始将任务中的每一个伤亡都视为个人的责任。内心独白充满了对他人遭遇的感同身受。',
        unlockedContent: ['dialogue-ling-empathy', 'skill-inspire-allies'],
      },
      {
        min: 60,
        max: 100,
        label: '人性光辉',
        narrativeTone: '凌成为了团队的精神支柱。她相信每一个生命都值得被拯救，哪怕代价是任务失败。',
        unlockedContent: ['ending-sacrifice', 'dialogue-ling-inspiring-speech', 'scene-ling-shield-innocent'],
      },
    ],
    affectsEndings: ['ending-cold-operative', 'ending-balanced-agent', 'ending-humanitarian', 'ending-sacrifice'],
    affectsNPCAttitudes: [
      { characterId: 'char-hacker-kai', threshold: -40, attitudeChange: '凯觉得凌过于冷血，减少非必要交流' },
      { characterId: 'char-hacker-kai', threshold: 30, attitudeChange: '凯被凌的人性化一面打动，主动分享个人故事' },
      { characterId: 'char-corporate-mei', threshold: -30, attitudeChange: '梅对凌的专业素养表示钦佩，但保持警惕' },
      { characterId: 'char-corporate-mei', threshold: 50, attitudeChange: '梅被凌的理想主义感染，重新思考自己的立场' },
      { characterId: 'char-director-wu', threshold: 40, attitudeChange: '吴主管认为凌变得"软弱"，考虑更换执行人' },
    ],
    gatesChoices: [
      { choiceOptionId: 'opt-sacrifice-civilian', requiredRange: { min: -100, max: -10 } },
      { choiceOptionId: 'opt-save-civilian', requiredRange: { min: 20, max: 100 } },
      { choiceOptionId: 'opt-emotional-decision', requiredRange: { min: 50, max: 100 } },
      { choiceOptionId: 'opt-tactical-retreat', requiredRange: { min: -100, max: 10 } },
    ],
    gradientColors: ['#4a0e4e', '#22c55e'],
    description: '衡量凌在决策时更倾向于机械般的效率计算还是人性化的共情判断。这个轴直接影响凌的内心独白风格、对话选项以及最终结局的走向。',
  },
  {
    id: 'moral-003',
    name: '信息透明度',
    negativeLabel: '独占真相',
    positiveLabel: '公开透明',
    currentValue: -20,
    initialValue: -50,
    zones: [
      {
        min: -100,
        max: -60,
        label: '独裁者',
        narrativeTone: '凌将所有情报牢牢掌握在自己手中，不信任任何人。队友只知道他们需要知道的最小信息。',
        unlockedContent: ['skill-information-monopoly', 'dialogue-ling-secretive'],
      },
      {
        min: -59,
        max: -20,
        label: '谨慎守密',
        narrativeTone: '凌有选择地分享信息，但核心机密只有她自己知道。这是特工的本能。',
      },
      {
        min: -19,
        max: 19,
        label: '有限透明',
        narrativeTone: '凌开始意识到信息共享的价值，但仍对关键情报保持谨慎。',
        unlockedContent: ['dialogue-ling-partial-briefing'],
      },
      {
        min: 20,
        max: 59,
        label: '开放协作',
        narrativeTone: '凌主动与团队成员分享大部分情报，信任集体决策的力量。',
        unlockedContent: ['skill-team-intel-sync', 'dialogue-team-strategy'],
      },
      {
        min: 60,
        max: 100,
        label: '完全透明',
        narrativeTone: '凌选择将所有真相公之于众，包括监控名单和奇美拉计划的全部细节。',
        unlockedContent: ['ending-public-disclosure', 'scene-ling-press-conference'],
      },
    ],
    affectsEndings: ['ending-shadow-control', 'ending-team-victory', 'ending-public-disclosure'],
    affectsNPCAttitudes: [
      { characterId: 'char-hacker-kai', threshold: 30, attitudeChange: '凯感受到凌的信任，回馈更多技术发现' },
      { characterId: 'char-hacker-kai', threshold: -40, attitudeChange: '凯对凌的信息封锁感到愤怒，考虑独立行动' },
      { characterId: 'char-corporate-mei', threshold: 20, attitudeChange: '梅认为凌值得信赖，分享更多企业内部信息' },
    ],
    gatesChoices: [
      { choiceOptionId: 'opt-withhold-intel', requiredRange: { min: -100, max: -10 } },
      { choiceOptionId: 'opt-share-with-team', requiredRange: { min: 10, max: 100 } },
      { choiceOptionId: 'opt-public-leak', requiredRange: { min: 60, max: 100 } },
    ],
    gradientColors: ['#1a1a2e', '#06b6d4'],
    description: '衡量凌在情报管理上的开放程度。偏向负极时，她是一个传统的情报人员——信息就是武器；偏向正极时，她相信透明和信任才是打败阴谋的真正力量。',
  },
];

// ─── 11. 路径时间预估 ─────────────────────────────────────
export const SEED_PATH_TIME_ESTIMATES: PathTimeEstimate[] = [
  {
    pathId: 'path-stealth-main',
    totalDuration: 945,
    segments: [
      {
        nodeId: 'N01',
        nodeLabel: '序章·霓虹夜幕',
        dialogueTime: 45,
        interactionTime: 10,
        qteTime: 0,
        totalTime: 55,
      },
      {
        nodeId: 'N02',
        nodeLabel: '任务简报',
        dialogueTime: 60,
        interactionTime: 15,
        qteTime: 0,
        totalTime: 75,
      },
      {
        nodeId: 'N03',
        nodeLabel: '进入路线？',
        dialogueTime: 30,
        interactionTime: 20,
        qteTime: 0,
        totalTime: 50,
      },
      {
        nodeId: 'N04',
        nodeLabel: '暗夜通道',
        dialogueTime: 40,
        interactionTime: 25,
        qteTime: 0,
        totalTime: 65,
      },
      {
        nodeId: 'N06',
        nodeLabel: '警卫逼近',
        dialogueTime: 15,
        interactionTime: 10,
        qteTime: 45,
        totalTime: 70,
      },
      {
        nodeId: 'N07',
        nodeLabel: '潜行判定',
        dialogueTime: 20,
        interactionTime: 30,
        qteTime: 0,
        totalTime: 50,
      },
      {
        nodeId: 'N08',
        nodeLabel: '数据到手',
        dialogueTime: 80,
        interactionTime: 20,
        qteTime: 0,
        totalTime: 100,
      },
      {
        nodeId: 'N10',
        nodeLabel: '结局A 幽灵归来',
        dialogueTime: 120,
        interactionTime: 10,
        qteTime: 0,
        totalTime: 130,
      },
    ],
    pacingLabel: 'moderate',
  },
  {
    pathId: 'path-combat-aggressive',
    totalDuration: 720,
    segments: [
      {
        nodeId: 'N01',
        nodeLabel: '序章·霓虹夜幕',
        dialogueTime: 45,
        interactionTime: 10,
        qteTime: 0,
        totalTime: 55,
      },
      {
        nodeId: 'N02',
        nodeLabel: '任务简报',
        dialogueTime: 40,
        interactionTime: 10,
        qteTime: 0,
        totalTime: 50,
      },
      {
        nodeId: 'N03',
        nodeLabel: '进入路线？',
        dialogueTime: 20,
        interactionTime: 15,
        qteTime: 0,
        totalTime: 35,
      },
      {
        nodeId: 'N05',
        nodeLabel: '换装渗透',
        dialogueTime: 30,
        interactionTime: 20,
        qteTime: 30,
        totalTime: 80,
      },
      {
        nodeId: 'N06',
        nodeLabel: '警卫逼近',
        dialogueTime: 10,
        interactionTime: 5,
        qteTime: 60,
        totalTime: 75,
      },
      {
        nodeId: 'N07',
        nodeLabel: '潜行判定（失败）',
        dialogueTime: 15,
        interactionTime: 10,
        qteTime: 0,
        totalTime: 25,
      },
      {
        nodeId: 'N09',
        nodeLabel: '身份暴露',
        dialogueTime: 35,
        interactionTime: 15,
        qteTime: 50,
        totalTime: 100,
      },
      {
        nodeId: 'N11',
        nodeLabel: '今夜失败',
        dialogueTime: 90,
        interactionTime: 10,
        qteTime: 0,
        totalTime: 100,
      },
    ],
    pacingLabel: 'fast',
  },
  {
    pathId: 'path-investigation-deep',
    totalDuration: 1380,
    segments: [
      {
        nodeId: 'N01',
        nodeLabel: '序章·霓虹夜幕',
        dialogueTime: 60,
        interactionTime: 15,
        qteTime: 0,
        totalTime: 75,
      },
      {
        nodeId: 'N02',
        nodeLabel: '任务简报',
        dialogueTime: 90,
        interactionTime: 30,
        qteTime: 0,
        totalTime: 120,
      },
      {
        nodeId: 'N03',
        nodeLabel: '暗巷遭遇线人（完整对话）',
        dialogueTime: 120,
        interactionTime: 40,
        qteTime: 0,
        totalTime: 160,
      },
      {
        nodeId: 'N04',
        nodeLabel: '暗夜通道（含搜证）',
        dialogueTime: 50,
        interactionTime: 60,
        qteTime: 0,
        totalTime: 110,
      },
      {
        nodeId: 'N06',
        nodeLabel: '警卫逼近',
        dialogueTime: 15,
        interactionTime: 10,
        qteTime: 45,
        totalTime: 70,
      },
      {
        nodeId: 'N07',
        nodeLabel: '潜行判定',
        dialogueTime: 25,
        interactionTime: 30,
        qteTime: 0,
        totalTime: 55,
      },
      {
        nodeId: 'N08',
        nodeLabel: '数据到手（含推理）',
        dialogueTime: 100,
        interactionTime: 60,
        qteTime: 0,
        totalTime: 160,
      },
      {
        nodeId: 'N12',
        nodeLabel: '情报分析站',
        dialogueTime: 80,
        interactionTime: 50,
        qteTime: 0,
        totalTime: 130,
      },
      {
        nodeId: 'N20',
        nodeLabel: '推理·奇美拉真相',
        dialogueTime: 90,
        interactionTime: 70,
        qteTime: 0,
        totalTime: 160,
      },
      {
        nodeId: 'N10',
        nodeLabel: '结局A 幽灵归来（完整）',
        dialogueTime: 150,
        interactionTime: 20,
        qteTime: 0,
        totalTime: 170,
      },
    ],
    pacingLabel: 'slow',
  },
];
