// ChaseDream Creator Studio — Project Seed Data

import type { Project, FactoryTask } from '../types/project';

export const PROJECTS: Project[] = [
  {
    id: 'ghost-protocol',
    title: '幽灵协议',
    genre: 'Cyberpunk · 间谍惊悚',
    cover: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
    status: 'in_progress',
    healthScore: 100,
    healthLabel: 'HEALTH: 100%',
    healthType: 'success',
    progress: 74,
    stage1: 100,
    stage2: 100,
    stage3: 60,
    chapters: 1,
    nodes: 11,
    branches: 2,
    endings: 2,
    lastEdited: '10m ago',
  },
  {
    id: 'cabinet-absurdity',
    title: '荒诞内阁',
    genre: 'Mystery · 心理悬疑',
    cover: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80',
    status: 'idle',
    healthScore: 62,
    healthLabel: 'WARN: 3 ERR',
    healthType: 'error',
    progress: 46,
    stage1: 100,
    stage2: 40,
    stage3: 0,
    chapters: 1,
    nodes: 7,
    branches: 4,
    endings: 0,
    lastEdited: 'Yesterday',
    errors: 3,
  },
  {
    id: 'fusion-frontier',
    title: '聚变边疆',
    genre: 'Sci-Fi · 硬科幻',
    cover: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    status: 'draft',
    healthScore: 20,
    healthLabel: 'DRAFT',
    healthType: 'warning',
    progress: 20,
    stage1: 100,
    stage2: 0,
    stage3: 0,
    chapters: 1,
    nodes: 5,
    branches: 0,
    endings: 0,
    lastEdited: '3d ago',
  },
];

// AI Factory task steps
export const FACTORY_TASKS: FactoryTask[] = [
  { id: 'outline', label: '提取故事大纲', status: 'done', result: '1章·8场·主线确认' },
  { id: 'characters', label: '提取角色设定', status: 'done', result: '艾拉·线人·反派主管' },
  { id: 'scenes', label: '提取场景设定', status: 'done', result: '霓虹街道·地下酒吧等6处' },
  { id: 'props', label: '提取道具设定', status: 'done', result: '追踪芯片·变声器等9件' },
  { id: 'nodes', label: '生成互动节点', status: 'running', result: undefined },
  { id: 'choices', label: '生成选择项与变量', status: 'pending' },
  { id: 'endings', label: '生成结局', status: 'pending' },
  { id: 'logic', label: '逻辑检查', status: 'pending' },
  { id: 'assets_req', label: '生成素材需求', status: 'pending' },
  { id: 'publish_check', label: '发布前检查', status: 'pending' },
];
