/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionRouteImport } from './routes/version'
import { Route as StoryOverviewRouteImport } from './routes/story-overview'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScriptRouteImport } from './routes/script'
import { Route as QteEditorRouteImport } from './routes/qte-editor'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as PlaytRouteImport } from './routes/playt'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ParseRouteImport } from './routes/parse'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as NodeCanvasRouteImport } from './routes/node-canvas'
import { Route as MyWorksRouteImport } from './routes/my-works'
import { Route as InteractionRouteImport } from './routes/interaction'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as DetroitRouteImport } from './routes/detroit'
import { Route as DebuggerRouteImport } from './routes/debugger'
import { Route as CollabRouteImport } from './routes/collab'
import { Route as CinematicRouteImport } from './routes/cinematic'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AssetLibraryRouteImport } from './routes/asset-library'
import { Route as IndexRouteImport } from './routes/index'

const VersionRoute = VersionRouteImport.update({
  id: '/version',
  path: '/version',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryOverviewRoute = StoryOverviewRouteImport.update({
  id: '/story-overview',
  path: '/story-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptRoute = ScriptRouteImport.update({
  id: '/script',
  path: '/script',
  getParentRoute: () => rootRouteImport,
} as any)
const QteEditorRoute = QteEditorRouteImport.update({
  id: '/qte-editor',
  path: '/qte-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaytRoute = PlaytRouteImport.update({
  id: '/playt',
  path: '/playt',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ParseRoute = ParseRouteImport.update({
  id: '/parse',
  path: '/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const NodeCanvasRoute = NodeCanvasRouteImport.update({
  id: '/node-canvas',
  path: '/node-canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorksRoute = MyWorksRouteImport.update({
  id: '/my-works',
  path: '/my-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionRoute = InteractionRouteImport.update({
  id: '/interaction',
  path: '/interaction',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const DetroitRoute = DetroitRouteImport.update({
  id: '/detroit',
  path: '/detroit',
  getParentRoute: () => rootRouteImport,
} as any)
const DebuggerRoute = DebuggerRouteImport.update({
  id: '/debugger',
  path: '/debugger',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabRoute = CollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const CinematicRoute = CinematicRouteImport.update({
  id: '/cinematic',
  path: '/cinematic',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetLibraryRoute = AssetLibraryRouteImport.update({
  id: '/asset-library',
  path: '/asset-library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asset-library': typeof AssetLibraryRoute
  '/assets': typeof AssetsRoute
  '/canvas': typeof CanvasRoute
  '/cinematic': typeof CinematicRoute
  '/collab': typeof CollabRoute
  '/debugger': typeof DebuggerRoute
  '/detroit': typeof DetroitRoute
  '/factory': typeof FactoryRoute
  '/interaction': typeof InteractionRoute
  '/my-works': typeof MyWorksRoute
  '/node-canvas': typeof NodeCanvasRoute
  '/nodes': typeof NodesRoute
  '/overview': typeof OverviewRoute
  '/parse': typeof ParseRoute
  '/pipeline': typeof PipelineRoute
  '/playt': typeof PlaytRoute
  '/publish': typeof PublishRoute
  '/qte-editor': typeof QteEditorRoute
  '/script': typeof ScriptRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/story-overview': typeof StoryOverviewRoute
  '/version': typeof VersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asset-library': typeof AssetLibraryRoute
  '/assets': typeof AssetsRoute
  '/canvas': typeof CanvasRoute
  '/cinematic': typeof CinematicRoute
  '/collab': typeof CollabRoute
  '/debugger': typeof DebuggerRoute
  '/detroit': typeof DetroitRoute
  '/factory': typeof FactoryRoute
  '/interaction': typeof InteractionRoute
  '/my-works': typeof MyWorksRoute
  '/node-canvas': typeof NodeCanvasRoute
  '/nodes': typeof NodesRoute
  '/overview': typeof OverviewRoute
  '/parse': typeof ParseRoute
  '/pipeline': typeof PipelineRoute
  '/playt': typeof PlaytRoute
  '/publish': typeof PublishRoute
  '/qte-editor': typeof QteEditorRoute
  '/script': typeof ScriptRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/story-overview': typeof StoryOverviewRoute
  '/version': typeof VersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asset-library': typeof AssetLibraryRoute
  '/assets': typeof AssetsRoute
  '/canvas': typeof CanvasRoute
  '/cinematic': typeof CinematicRoute
  '/collab': typeof CollabRoute
  '/debugger': typeof DebuggerRoute
  '/detroit': typeof DetroitRoute
  '/factory': typeof FactoryRoute
  '/interaction': typeof InteractionRoute
  '/my-works': typeof MyWorksRoute
  '/node-canvas': typeof NodeCanvasRoute
  '/nodes': typeof NodesRoute
  '/overview': typeof OverviewRoute
  '/parse': typeof ParseRoute
  '/pipeline': typeof PipelineRoute
  '/playt': typeof PlaytRoute
  '/publish': typeof PublishRoute
  '/qte-editor': typeof QteEditorRoute
  '/script': typeof ScriptRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/story-overview': typeof StoryOverviewRoute
  '/version': typeof VersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asset-library'
    | '/assets'
    | '/canvas'
    | '/cinematic'
    | '/collab'
    | '/debugger'
    | '/detroit'
    | '/factory'
    | '/interaction'
    | '/my-works'
    | '/node-canvas'
    | '/nodes'
    | '/overview'
    | '/parse'
    | '/pipeline'
    | '/playt'
    | '/publish'
    | '/qte-editor'
    | '/script'
    | '/settings'
    | '/simulator'
    | '/story-overview'
    | '/version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asset-library'
    | '/assets'
    | '/canvas'
    | '/cinematic'
    | '/collab'
    | '/debugger'
    | '/detroit'
    | '/factory'
    | '/interaction'
    | '/my-works'
    | '/node-canvas'
    | '/nodes'
    | '/overview'
    | '/parse'
    | '/pipeline'
    | '/playt'
    | '/publish'
    | '/qte-editor'
    | '/script'
    | '/settings'
    | '/simulator'
    | '/story-overview'
    | '/version'
  id:
    | '__root__'
    | '/'
    | '/asset-library'
    | '/assets'
    | '/canvas'
    | '/cinematic'
    | '/collab'
    | '/debugger'
    | '/detroit'
    | '/factory'
    | '/interaction'
    | '/my-works'
    | '/node-canvas'
    | '/nodes'
    | '/overview'
    | '/parse'
    | '/pipeline'
    | '/playt'
    | '/publish'
    | '/qte-editor'
    | '/script'
    | '/settings'
    | '/simulator'
    | '/story-overview'
    | '/version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetLibraryRoute: typeof AssetLibraryRoute
  AssetsRoute: typeof AssetsRoute
  CanvasRoute: typeof CanvasRoute
  CinematicRoute: typeof CinematicRoute
  CollabRoute: typeof CollabRoute
  DebuggerRoute: typeof DebuggerRoute
  DetroitRoute: typeof DetroitRoute
  FactoryRoute: typeof FactoryRoute
  InteractionRoute: typeof InteractionRoute
  MyWorksRoute: typeof MyWorksRoute
  NodeCanvasRoute: typeof NodeCanvasRoute
  NodesRoute: typeof NodesRoute
  OverviewRoute: typeof OverviewRoute
  ParseRoute: typeof ParseRoute
  PipelineRoute: typeof PipelineRoute
  PlaytRoute: typeof PlaytRoute
  PublishRoute: typeof PublishRoute
  QteEditorRoute: typeof QteEditorRoute
  ScriptRoute: typeof ScriptRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  StoryOverviewRoute: typeof StoryOverviewRoute
  VersionRoute: typeof VersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/version': {
      id: '/version'
      path: '/version'
      fullPath: '/version'
      preLoaderRoute: typeof VersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-overview': {
      id: '/story-overview'
      path: '/story-overview'
      fullPath: '/story-overview'
      preLoaderRoute: typeof StoryOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/script': {
      id: '/script'
      path: '/script'
      fullPath: '/script'
      preLoaderRoute: typeof ScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qte-editor': {
      id: '/qte-editor'
      path: '/qte-editor'
      fullPath: '/qte-editor'
      preLoaderRoute: typeof QteEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playt': {
      id: '/playt'
      path: '/playt'
      fullPath: '/playt'
      preLoaderRoute: typeof PlaytRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parse': {
      id: '/parse'
      path: '/parse'
      fullPath: '/parse'
      preLoaderRoute: typeof ParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/node-canvas': {
      id: '/node-canvas'
      path: '/node-canvas'
      fullPath: '/node-canvas'
      preLoaderRoute: typeof NodeCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-works': {
      id: '/my-works'
      path: '/my-works'
      fullPath: '/my-works'
      preLoaderRoute: typeof MyWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interaction': {
      id: '/interaction'
      path: '/interaction'
      fullPath: '/interaction'
      preLoaderRoute: typeof InteractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detroit': {
      id: '/detroit'
      path: '/detroit'
      fullPath: '/detroit'
      preLoaderRoute: typeof DetroitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debugger': {
      id: '/debugger'
      path: '/debugger'
      fullPath: '/debugger'
      preLoaderRoute: typeof DebuggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab': {
      id: '/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof CollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinematic': {
      id: '/cinematic'
      path: '/cinematic'
      fullPath: '/cinematic'
      preLoaderRoute: typeof CinematicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-library': {
      id: '/asset-library'
      path: '/asset-library'
      fullPath: '/asset-library'
      preLoaderRoute: typeof AssetLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetLibraryRoute: AssetLibraryRoute,
  AssetsRoute: AssetsRoute,
  CanvasRoute: CanvasRoute,
  CinematicRoute: CinematicRoute,
  CollabRoute: CollabRoute,
  DebuggerRoute: DebuggerRoute,
  DetroitRoute: DetroitRoute,
  FactoryRoute: FactoryRoute,
  InteractionRoute: InteractionRoute,
  MyWorksRoute: MyWorksRoute,
  NodeCanvasRoute: NodeCanvasRoute,
  NodesRoute: NodesRoute,
  OverviewRoute: OverviewRoute,
  ParseRoute: ParseRoute,
  PipelineRoute: PipelineRoute,
  PlaytRoute: PlaytRoute,
  PublishRoute: PublishRoute,
  QteEditorRoute: QteEditorRoute,
  ScriptRoute: ScriptRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  StoryOverviewRoute: StoryOverviewRoute,
  VersionRoute: VersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
